forecaster:
  port: 8001
  ARIMA_AVAILABLE: true
  PROPHET_AVAILABLE: false
  CHRONOS_AVAILABLE: false
  CHRONOS_MODEL: amazon/chronos-t5-tiny
triton:
  host: triton
  grpc_port: 8001
  http_port: 8000
